# print('This quote is from \nIrish poet Oscar Wilde:\n"Music makes one feel so romantic\n- at least it always gets on one\'s nerves – \nwhich is the same thing nowadays."')
# a = 9/5
# print(a)
# b=695%20
# print(b)
# c=248 % 100 / 5
# print(c)
d= 6 + (18 % (17 - 12))
print(d)
print(6 + (18 % (17 - 12)) )
number = int(input("calculate a number: "))

if number % 2 == 0:
    print("its an even number")
else:
    print("not an even  number")